project:
  type: website
  output-dir: docs

website:
  title: "Groundwater Spatial Modeling Challenge"
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: features.qmd
      - href: about.qmd
    tools:
      - icon: github
        href: https://twitter.com

format:
  html:
    theme: sandstone
    toc: true
    page-layout: full