project:
  type: website
  output-dir: docs

website:
  title: "Groundwater Spatial Modeling Challenge"
  repo-url: https://github.com/Groundwater-Spatial-Modeling-Challenge/challenge2024
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true