---
title: "Features"
---

```{r}
#| echo: FALSE
#| output: FALSE

library(readr)
library(dplyr)
library(DT)

metadata_features <- read_csv("features.csv")

```

The following table provides relevant information about the `r nrow(metadata_features)` features. Either all or an arbitrary subset of features can be used for modeling.

::: {.callout-tip}

The following features are available for multiple spatial scales:

- feat_topo_eumohp_\<feature name>(1, 2, 3, 4, 5)
- feat_topo_amatulli_\<feature name>(1km, 5km, 10km, 50km, 100km)\<suffix>

So please be aware of that, when subsetting features!

:::

```{r}
#| echo: FALSE
#| out-width: '1000px'

metadata_features <- metadata_features |>
  select(-`data source local`, -citation) |>
  mutate(`data source` = if_else(is.na(`data source`), "", stringr::str_glue("<a href='{`data source`}'>{`data source`}</a>"))) |> 
  rename(`Source / Further Information` = `data source`) |> 
  rename_with(stringr::str_to_title, everything())

metadata_features |> 
  datatable(
    width = "3000px",
    filter = "top",
    options = list(
      autoWidth = TRUE,
      columnDefs = list(list(width = '200px', targets = list(2))),
      scrollY = "800px",
      lengthMenu = list(c(25, 100, -1), c("25", "100", "All")),
      pageLength = nrow(metadata_features)
    ),
    escape = FALSE
  ) |> 
   formatStyle(columns = 1:ncol(metadata_features), fontSize = '70%')
```


